// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PalletTimeLine.Api.Infrastructure.Data;

#nullable disable

namespace PalletTimeLine.Api.Migrations
{
    [DbContext(typeof(PalletTimelineDbContext))]
    [Migration("20260512142637_AddIsSystemOnlyToUser")]
    partial class AddIsSystemOnlyToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("idx_auditlog_changedby");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_auditlog_timestamp");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_auditlog_entitytype_entityid");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.CostItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("Costs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-aaaaaaaaaaaa"),
                            Amount = 670m,
                            Category = "supplies",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Zakupy spożywcze i przemysłowe cz.1"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-bbbbbbbbbbbb"),
                            Amount = 600m,
                            Category = "merch",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Torby"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-cccccccccccc"),
                            Amount = 160m,
                            Category = "merch",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Wlepki"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-dddddddddddd"),
                            Amount = 3300m,
                            Category = "merch",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Koszulki"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-eeeeeeeeeeee"),
                            Amount = 177m,
                            Category = "supplies",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Zakupy spożywcze cz.2"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-ffffffffffff"),
                            Amount = 425m,
                            Category = "build",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Plandeka"
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.EditionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Editions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-8888-7777-6666-555555555555"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edycja 2025",
                            EndDate = new DateOnly(2025, 8, 10),
                            Name = "PaletStock 2025",
                            StartDate = new DateOnly(2025, 8, 7),
                            Status = "Active",
                            Year = 2025
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.RevenueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("Revenues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-7777-7777-7777-111111111111"),
                            Amount = 540m,
                            Category = "donations",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Świnka skarbonka"
                        },
                        new
                        {
                            Id = new Guid("22222222-8888-8888-8888-222222222222"),
                            Amount = 3300m,
                            Category = "sponsors",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Sponsorzy — Radek"
                        },
                        new
                        {
                            Id = new Guid("33333333-9999-9999-9999-333333333333"),
                            Amount = 1200m,
                            Category = "sponsors",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Sponsorzy — Konrad"
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-aaaa-aaaa-444444444444"),
                            Amount = 2660m,
                            Category = "donations",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Zrzutka"
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("idx_taskcomment_authorid");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_taskcomment_createdat");

                    b.HasIndex("TaskItemId")
                        .HasDatabaseName("idx_taskcomment_taskitemid");

                    b.ToTable("TaskComments", (string)null);
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = "site",
                            CompleteDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Do połowy czerwca ogarnięcie gruzu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Category = "site",
                            CompleteDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "InProgress",
                            Title = "Ogrodzenie i znaki zakazu wokół gruzu"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Category = "admin",
                            CompleteDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "podpytać czy to jest legalne",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "InProgress",
                            Title = "Loteria fantowa — sprawdzić legalność"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Category = "supplies",
                            CompleteDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "NotStarted",
                            Title = "Zapytać Matczyn o wynajem nalewaka"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "odbiór 01.08, oddajemy 11–13.08",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Dogadać 300 europalet"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Category = "site",
                            CompleteDate = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mateusz Prakowski wyrówna teren",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Wyrównanie terenu — Anasiewicz"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Category = "supplies",
                            CompleteDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Paliwo z Admarem"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Słupki od Gonza"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Ogrodzenie metalowe do backstage"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ustawianie 3 sierpnia",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Słupki oświetleniowe"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            Category = "finance",
                            CompleteDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ok. 700 zł",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Sprawdzić kasę z poprzedniej edycji"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666667"),
                            Category = "promo",
                            CompleteDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Promocja zbiórki"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777778"),
                            Category = "promo",
                            CompleteDate = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "InProgress",
                            Title = "Posty na stronie"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888889"),
                            Category = "merch",
                            CompleteDate = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Wycena koszulek"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999990"),
                            Category = "merch",
                            CompleteDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Wlepki"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "Done",
                            Title = "Naprawa namiotu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "do 2 sierpnia",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "NotStarted",
                            Title = "Zwożenie palet"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "NotStarted",
                            Title = "Początek budowy"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd4"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "NotStarted",
                            Title = "Scena ma stać"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5"),
                            Category = "build",
                            CompleteDate = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Priority = "Ordinary",
                            Status = "NotStarted",
                            Title = "Prysznic, woda"
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "System",
                            FirstName = "System",
                            IsActive = false,
                            IsSystemOnly = true,
                            LastName = "",
                            UserName = "system"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DisplayName = "Konrad",
                            FirstName = "Konrad",
                            IsActive = true,
                            IsSystemOnly = false,
                            LastName = "Kowalski",
                            UserName = "konrad"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DisplayName = "Stalowy",
                            FirstName = "Stalowy",
                            IsActive = true,
                            IsSystemOnly = false,
                            LastName = "Bizon",
                            UserName = "stalowy"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DisplayName = "Kinia",
                            FirstName = "Kinia",
                            IsActive = true,
                            IsSystemOnly = false,
                            LastName = "Nowak",
                            UserName = "kinia"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DisplayName = "Asia",
                            FirstName = "Asia",
                            IsActive = true,
                            IsSystemOnly = false,
                            LastName = "Nowak",
                            UserName = "asia"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            DisplayName = "Radosław",
                            FirstName = "Radosław",
                            IsActive = true,
                            IsSystemOnly = false,
                            LastName = "Nowak",
                            UserName = "radoslaw"
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.WarehouseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("WarehouseItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-bbbb-bbbb-bbbb-555555555555"),
                            Category = "lighting",
                            Location = "Misio",
                            Name = "Halogen LED z czujnikiem ruchu",
                            Note = "2 nowe",
                            Qty = 6m,
                            Unit = "szt"
                        },
                        new
                        {
                            Id = new Guid("66666666-cccc-cccc-cccc-666666666666"),
                            Category = "signs",
                            Location = "Misio",
                            Name = "Znak 'Teren prywatny' laminowany",
                            Note = "",
                            Qty = 1m,
                            Unit = "szt"
                        },
                        new
                        {
                            Id = new Guid("77777777-dddd-dddd-dddd-777777777777"),
                            Category = "other",
                            Location = "Misio",
                            Name = "Megafon Rebel",
                            Note = "Naprawiony",
                            Qty = 1m,
                            Unit = "szt"
                        },
                        new
                        {
                            Id = new Guid("88888888-eeee-eeee-eeee-888888888888"),
                            Category = "lighting",
                            Location = "Misio",
                            Name = "Lampki najazdowe solarne",
                            Note = "Pod parking",
                            Qty = 12m,
                            Unit = "szt"
                        },
                        new
                        {
                            Id = new Guid("99999999-ffff-ffff-ffff-999999999999"),
                            Category = "supplies",
                            Location = "Stalowy",
                            Name = "Taśma biało-czerwona",
                            Note = "Trzeba jeszcze ~750 m",
                            Qty = 500m,
                            Unit = "m"
                        });
                });

            modelBuilder.Entity("TaskItemUser", b =>
                {
                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskItemUser");

                    b.HasData(
                        new
                        {
                            TaskItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("11111111-1111-1111-1111-111111111112"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("22222222-2222-2222-2222-222222222223"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("33333333-3333-3333-3333-333333333334"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("44444444-4444-4444-4444-444444444445"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("55555555-5555-5555-5555-555555555556"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            TaskItemId = new Guid("55555555-5555-5555-5555-555555555556"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            TaskItemId = new Guid("66666666-6666-6666-6666-666666666667"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            TaskItemId = new Guid("66666666-6666-6666-6666-666666666667"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            TaskItemId = new Guid("77777777-7777-7777-7777-777777777778"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            TaskItemId = new Guid("77777777-7777-7777-7777-777777777778"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            TaskItemId = new Guid("88888888-8888-8888-8888-888888888889"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            TaskItemId = new Guid("99999999-9999-9999-9999-999999999990"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            TaskItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd4"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.CostItem", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Domain.Entities.EditionItem", "Edition")
                        .WithMany("Outcomes")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.RevenueItem", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Domain.Entities.EditionItem", "Edition")
                        .WithMany("Incomes")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PalletTimeLine.Api.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Comments")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Domain.Entities.EditionItem", "Edition")
                        .WithMany("Tasks")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("TaskItemUser", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PalletTimeLine.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.EditionItem", b =>
                {
                    b.Navigation("Incomes");

                    b.Navigation("Outcomes");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
