// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PalletTimeLine.Api.Data;

#nullable disable

namespace PalletTimeLine.Api.Migrations
{
    [DbContext(typeof(PalletTimelineDbContext))]
    [Migration("20260506132340_RemoveEngColumn")]
    partial class RemoveEngColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PalletTimeLine.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("idx_auditlog_changedby");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_auditlog_timestamp");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_auditlog_entitytype_entityid");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.CostItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("Costs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-aaaaaaaaaaaa"),
                            Amount = 670m,
                            Category = "supplies",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Zakupy spożywcze i przemysłowe cz.1"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-bbbbbbbbbbbb"),
                            Amount = 600m,
                            Category = "merch",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Torby"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-cccccccccccc"),
                            Amount = 160m,
                            Category = "merch",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Wlepki"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-dddddddddddd"),
                            Amount = 3300m,
                            Category = "merch",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Koszulki"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-eeeeeeeeeeee"),
                            Amount = 177m,
                            Category = "supplies",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Zakupy spożywcze cz.2"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-ffffffffffff"),
                            Amount = 425m,
                            Category = "build",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Plandeka"
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.EditionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Editions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-8888-7777-6666-555555555555"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edycja 2025",
                            EndDate = new DateOnly(2025, 8, 10),
                            Name = "PaletStock 2025",
                            StartDate = new DateOnly(2025, 8, 7),
                            Status = "Active",
                            Year = 2025
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.RevenueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("Revenues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-7777-7777-7777-111111111111"),
                            Amount = 540m,
                            Category = "donations",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Świnka skarbonka"
                        },
                        new
                        {
                            Id = new Guid("22222222-8888-8888-8888-222222222222"),
                            Amount = 3300m,
                            Category = "sponsors",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Sponsorzy — Radek"
                        },
                        new
                        {
                            Id = new Guid("33333333-9999-9999-9999-333333333333"),
                            Amount = 1200m,
                            Category = "sponsors",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Sponsorzy — Konrad"
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-aaaa-aaaa-444444444444"),
                            Amount = 2660m,
                            Category = "donations",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Name = "Zrzutka"
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = "site",
                            Date = "2025-06-15",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "done",
                            Task = "Do połowy czerwca ogarnięcie gruzu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Category = "site",
                            Date = "2025-07-25",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "in-progress",
                            Task = "Ogrodzenie i znaki zakazu wokół gruzu"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Category = "admin",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Note = "podpytać czy to jest legalne",
                            Status = "in-progress",
                            Task = "Loteria fantowa — sprawdzić legalność"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Category = "supplies",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "todo",
                            Task = "Zapytać Matczyn o wynajem nalewaka"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Category = "build",
                            Date = "2025-08-01",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Note = "odbiór 01.08, oddajemy 11–13.08",
                            Status = "done",
                            Task = "Dogadać 300 europalet"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Category = "site",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Note = "Mateusz Prakowski wyrówna teren",
                            Status = "done",
                            Task = "Wyrównanie terenu — Anasiewicz"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Category = "supplies",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "done",
                            Task = "Paliwo z Admarem"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Category = "build",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "done",
                            Task = "Słupki od Gonza"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            Category = "build",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "done",
                            Task = "Ogrodzenie metalowe do backstage"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            Category = "build",
                            Date = "2025-08-01",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Note = "ustawianie 3 sierpnia",
                            Status = "done",
                            Task = "Słupki oświetleniowe"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            Category = "finance",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Note = "ok. 700 zł",
                            Status = "done",
                            Task = "Sprawdzić kasę z poprzedniej edycji"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666667"),
                            Category = "promo",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "done",
                            Task = "Promocja zbiórki"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777778"),
                            Category = "promo",
                            Date = "2025-07-12",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "in-progress",
                            Task = "Posty na stronie"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888889"),
                            Category = "merch",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "done",
                            Task = "Wycena koszulek"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999990"),
                            Category = "merch",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "done",
                            Task = "Wlepki"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Category = "build",
                            Date = "2025-06-30",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "done",
                            Task = "Naprawa namiotu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Category = "build",
                            Date = "2025-07-26",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Note = "do 2 sierpnia",
                            Status = "todo",
                            Task = "Zwożenie palet"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            Category = "build",
                            Date = "2025-08-04",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "todo",
                            Task = "Początek budowy"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd4"),
                            Category = "build",
                            Date = "2025-08-07",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "todo",
                            Task = "Scena ma stać"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5"),
                            Category = "build",
                            Date = "2025-08-05",
                            EditionId = new Guid("99999999-8888-7777-6666-555555555555"),
                            Status = "todo",
                            Task = "Prysznic, woda"
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DisplayName = "Konrad",
                            FirstName = "Konrad",
                            IsActive = true,
                            LastName = "Kowalski",
                            UserName = "konrad"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DisplayName = "Stalowy",
                            FirstName = "Stalowy",
                            IsActive = true,
                            LastName = "Bizon",
                            UserName = "stalowy"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DisplayName = "Kinia",
                            FirstName = "Kinia",
                            IsActive = true,
                            LastName = "Nowak",
                            UserName = "kinia"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DisplayName = "Asia",
                            FirstName = "Asia",
                            IsActive = true,
                            LastName = "Nowak",
                            UserName = "asia"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            DisplayName = "Radosław",
                            FirstName = "Radosław",
                            IsActive = true,
                            LastName = "Nowak",
                            UserName = "radoslaw"
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.WarehouseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WarehouseItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-bbbb-bbbb-bbbb-555555555555"),
                            Category = "lighting",
                            Location = "Misio",
                            Name = "Halogen LED z czujnikiem ruchu",
                            Note = "2 nowe",
                            Qty = 6m,
                            Unit = "szt"
                        },
                        new
                        {
                            Id = new Guid("66666666-cccc-cccc-cccc-666666666666"),
                            Category = "signs",
                            Location = "Misio",
                            Name = "Znak 'Teren prywatny' laminowany",
                            Note = "",
                            Qty = 1m,
                            Unit = "szt"
                        },
                        new
                        {
                            Id = new Guid("77777777-dddd-dddd-dddd-777777777777"),
                            Category = "other",
                            Location = "Misio",
                            Name = "Megafon Rebel",
                            Note = "Naprawiony",
                            Qty = 1m,
                            Unit = "szt"
                        },
                        new
                        {
                            Id = new Guid("88888888-eeee-eeee-eeee-888888888888"),
                            Category = "lighting",
                            Location = "Misio",
                            Name = "Lampki najazdowe solarne",
                            Note = "Pod parking",
                            Qty = 12m,
                            Unit = "szt"
                        },
                        new
                        {
                            Id = new Guid("99999999-ffff-ffff-ffff-999999999999"),
                            Category = "supplies",
                            Location = "Stalowy",
                            Name = "Taśma biało-czerwona",
                            Note = "Trzeba jeszcze ~750 m",
                            Qty = 500m,
                            Unit = "m"
                        });
                });

            modelBuilder.Entity("TaskItemUser", b =>
                {
                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskItemUser");

                    b.HasData(
                        new
                        {
                            TaskItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("11111111-1111-1111-1111-111111111112"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("22222222-2222-2222-2222-222222222223"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("33333333-3333-3333-3333-333333333334"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            TaskItemId = new Guid("44444444-4444-4444-4444-444444444445"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("55555555-5555-5555-5555-555555555556"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            TaskItemId = new Guid("55555555-5555-5555-5555-555555555556"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            TaskItemId = new Guid("66666666-6666-6666-6666-666666666667"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            TaskItemId = new Guid("66666666-6666-6666-6666-666666666667"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            TaskItemId = new Guid("77777777-7777-7777-7777-777777777778"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            TaskItemId = new Guid("77777777-7777-7777-7777-777777777778"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            TaskItemId = new Guid("88888888-8888-8888-8888-888888888889"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            TaskItemId = new Guid("99999999-9999-9999-9999-999999999990"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            TaskItemId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd4"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            TaskItemId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.AuditLog", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.CostItem", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Models.EditionItem", "Edition")
                        .WithMany("Outcomes")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.RevenueItem", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Models.EditionItem", "Edition")
                        .WithMany("Incomes")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.TaskItem", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Models.EditionItem", "Edition")
                        .WithMany("Tasks")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("TaskItemUser", b =>
                {
                    b.HasOne("PalletTimeLine.Api.Models.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PalletTimeLine.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PalletTimeLine.Api.Models.EditionItem", b =>
                {
                    b.Navigation("Incomes");

                    b.Navigation("Outcomes");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
