/* global React */
const { useState, useMemo, useEffect } = React;

// ===== i18n =====
const I18N = {
  pl: {
    appTitle: "PalletTimeLine",
    appSub: "Festiwal 2025",
    navOverview: "Przegląd",
    navTasks: "Zadania i kalendarz",
    navCosts: "Koszty",
    navWarehouse: "Magazyn",
    sections: "Sekcje",
    daysToFestival: "Dni do festiwalu",
    festivalDate: "8–9 sierpnia 2025",
    print: "Drukuj",
    add: "Dodaj",
    search: "Szukaj…",
    tabList: "Lista zadań",
    tabGantt: "Harmonogram",
    all: "Wszystkie",
    person: "Osoba",
    category: "Kategoria",
    location: "Lokalizacja",
    statusTodo: "Nie rozpoczęto",
    statusInProgress: "W trakcie",
    statusDone: "Wykonane",
    statusCancelled: "Anulowane",
    revenue: "Przychody",
    costs: "Koszty",
    balance: "Bilans",
    topCosts: "Top wydatki",
    costsByCategory: "Koszty wg kategorii",
    topRevenue: "Top przychody",
    revenueByCategory: "Przychody wg kategorii",
    revenueVsCosts: "Przychody vs koszty",
    item: "Pozycja",
    amount: "Kwota",
    qty: "Ilość",
    note: "Szczegóły",
    name: "Nazwa",
    date: "Termin",
    assignees: "Przypisani",
    status: "Status",
    overdue: "po terminie",
    noDate: "—",
    total: "Razem",
    overview: "Przegląd",
    tasksTitle: "Zadania i harmonogram",
    costsTitle: "Koszty i przychody",
    warehouseTitle: "Magazyn",
    overviewSub: "Stan przygotowań",
    tasksDone: "Zadań wykonanych",
    of: "z",
    nextMilestone: "Najbliższy kamień milowy",
    upcoming: "Nadchodzące zadania",
    recentlyDone: "Ostatnio wykonane",
    cancelled: "Anulowane",
    inProgress: "W trakcie",
    todo: "Do zrobienia",
    done: "Wykonane",
    days: ["Pon","Wt","Śr","Czw","Pt","Sob","Ndz"],
    months: ["sty","lut","mar","kwi","maj","cze","lip","sie","wrz","paź","lis","gru"],
    festivalBand: "Festiwal",
  },
  en: {
    appTitle: "PalletTimeLine",
    appSub: "Festival 2025",
    navOverview: "Overview",
    navTasks: "Tasks & calendar",
    navCosts: "Costs",
    navWarehouse: "Inventory",
    sections: "Sections",
    daysToFestival: "Days to festival",
    festivalDate: "Aug 8–9, 2025",
    print: "Print",
    add: "Add",
    search: "Search…",
    tabList: "Task list",
    tabGantt: "Timeline",
    all: "All",
    person: "Person",
    category: "Category",
    location: "Location",
    statusTodo: "Not started",
    statusInProgress: "In progress",
    statusDone: "Done",
    statusCancelled: "Cancelled",
    revenue: "Revenue",
    costs: "Costs",
    balance: "Balance",
    topCosts: "Top expenses",
    costsByCategory: "Costs by category",
    topRevenue: "Top revenue",
    revenueByCategory: "Revenue by category",
    revenueVsCosts: "Revenue vs costs",
    item: "Item",
    amount: "Amount",
    qty: "Qty",
    note: "Details",
    name: "Name",
    date: "Due",
    assignees: "Assignees",
    status: "Status",
    overdue: "overdue",
    noDate: "—",
    total: "Total",
    overview: "Overview",
    tasksTitle: "Tasks & schedule",
    costsTitle: "Costs & revenue",
    warehouseTitle: "Inventory",
    overviewSub: "Preparation status",
    tasksDone: "Tasks done",
    of: "of",
    nextMilestone: "Next milestone",
    upcoming: "Upcoming tasks",
    recentlyDone: "Recently done",
    cancelled: "Cancelled",
    inProgress: "In progress",
    todo: "To do",
    done: "Done",
    days: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
    months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
    festivalBand: "Festival",
  },
};

// ===== utils =====
const fmtPLN = (n) => new Intl.NumberFormat("pl-PL").format(Math.round(n)) + " zł";
const parseISO = (s) => { if (!s) return null; const [y,m,d] = s.split("-").map(Number); return new Date(y, m-1, d); };
const isoDate = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const fmtDate = (s, lang) => {
  const d = parseISO(s); if (!d) return "";
  const t = I18N[lang];
  return `${d.getDate()} ${t.months[d.getMonth()]}`;
};
const initials = (name) => name.split(/\s+/).map(w => w[0]).join("").slice(0,2).toUpperCase();

// Pretend "today" = July 22, 2025 (~17 days before festival)
const TODAY = new Date(2025, 6, 22);

window.I18N = I18N;
window.utils = { fmtPLN, parseISO, isoDate, fmtDate, initials, TODAY };
